[package]
name = "awrevim"
version = "0.1.0"
authors = ["Sirac <sirac@densa.software>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ropey = "1.1.0"
crossterm = "0.14.2"
